import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidenav from "@/components/Sidenav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex bg-white" style={inter.style}>
        <div className="grid grid-cols-[20%_auto] w-full flex-1">
          <Sidenav />
          {children}
        </div>
      </body>
    </html>
  );
}
